// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ssbzsiwjmjpapdlasjvy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzYnpzaXdqbWpwYXBkbGFzanZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxNzg5MTEsImV4cCI6MjA1OTc1NDkxMX0.bazTWWCyttRGQt3Y-LtQZSx0jC5o791FOui3wKYVGIk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});